class Cav {

    class cavObjectives {

    file = "cavFunctions\objectives";

        class patrolElim {};
    };

    class cavPlayer {

    file = "cavFunctions\player";

        class addActions {};
        class createSpawner {};
        class halo {};
    };

    class cavServer
    {

    file = "cavFunctions\server";

        class calculateForce {};
        class checkWater {};
        class createAO {};
        class handleAI {};
        class missionGenerate {};
        class spawnForce {};
        class spawnInfantryGroup {};
        class spawnObjective {};
    };
}
